name: Sast scan

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on:
  push:

jobs:
  SAST-SCA:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
    - uses: actions/checkout@v2
    - name: Perform Scan
    - uses: AppThreat/sast-scan-action@master      
    - name: Upload repors 
    - uses: actions/upload-artifact@v1
      with:
      name: reports
      path: reports 
  
  # DAST:
  #   runs-on: ubuntu-latest
  #   name: zap-web
  #   needs: SAST-SCA
  #   steps:
  #     - name: DAST(Zap)
  #       uses: zaproxy/action-full-scan@v0.4.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         docker_name: 'owasp/zap2docker-stable'
  #         target: 'http://zero.webappsecurity.com/'
  #         rules_file_name: '.zap/rules.tsv'
  #         cmd_options: 